# -*- coding: utf-8 -*-
"""
Phase 4: Maude 代码生成器。
将 normalized + validated IR → Maude 重写规则。

使用 _normalized 字段中的 Maude 映射结果生成代码。
只对 validator 标记为 can_generate 的规则生成实际代码；
其余生成注释占位。
"""
import logging
from typing import Any, Dict, List, Optional

from .dto import GenerationResult
from .validator import BatchValidationResult

logger = logging.getLogger(__name__)


class MaudeGenerator:
    """
    Phase 4: normalized IR → Maude 源代码。
    """

    def __init__(self, module_name: str = "RFC-RULES"):
        self.module_name = module_name

    def generate(
        self,
        normalized_ir: Dict[str, Any],
        validation: Optional[BatchValidationResult] = None,
    ) -> GenerationResult:
        """
        将 normalized IR 转换为 Maude 模块代码。
        如果提供了 validation，只对 can_generate 的规则生成代码。
        """
        rules = normalized_ir.get("semantic_rules", [])
        if not rules:
            return GenerationResult(
                success=False,
                errors=["No semantic_rules to generate"],
            )

        # 构建 rule_id → can_generate 映射
        gen_map: Dict[str, bool] = {}
        if validation:
            for vr in validation.rule_results:
                gen_map[vr.rule_id] = vr.can_generate

        try:
            lines = self._generate_module_header(normalized_ir)

            generated_count = 0
            skipped_count = 0
            for idx, rule in enumerate(rules):
                rule_id = rule.get("id", f"rule_{idx}")
                can_gen = gen_map.get(rule_id, True)  # 无 validation 时默认生成

                if can_gen:
                    lines.extend(self._generate_rule(rule))
                    generated_count += 1
                else:
                    lines.extend(self._generate_skip_comment(rule))
                    skipped_count += 1

            lines.append("")
            lines.append("endm")

            generated_code = "\n".join(lines)
            logger.debug(
                "[Generator] generated %d rules, skipped %d",
                generated_count, skipped_count,
            )
            return GenerationResult(
                success=True,
                generated_code=generated_code,
                target_name=f"{self.module_name.lower()}.maude",
            )
        except Exception as e:
            return GenerationResult(
                success=False,
                errors=[f"Maude generation failed: {str(e)}"],
            )

    # ─── 模块结构 ────────────────────────────────────────────────

    def _generate_module_header(self, ir: Dict[str, Any]) -> List[str]:
        """生成模块头部。"""
        rules_count = len(ir.get("semantic_rules", []))
        return [
            f"--- Generated by RFC Formalization Pipeline",
            f"--- semantic_rules count: {rules_count}",
            "",
            f"mod {self.module_name} is",
            "  protecting DNS .",
            "",
        ]

    # ─── 单条规则生成 ─────────────────────────────────────────────

    def _generate_rule(self, rule: Dict[str, Any]) -> List[str]:
        """
        将单条 semantic_rule 转换为 Maude 重写规则。
        优先使用 _normalized 中的映射结果。
        """
        rule_id = rule.get("id", "unknown-rule")
        norm = rule.get("_normalized", {})
        provenance = rule.get("provenance", {})
        source_doc = provenance.get("document", "N/A") if isinstance(provenance, dict) else "N/A"
        source_sec = provenance.get("section", "") if isinstance(provenance, dict) else ""

        # 从 _normalized 获取映射结果
        modality = norm.get("modality", "must")
        actor_type = norm.get("actor_type", "Actor")
        event_pattern = norm.get("event_pattern")
        action_types = norm.get("action_types", [])
        predicates = norm.get("predicates", [])

        # 原始字段（用于注释）
        event = rule.get("event", {})
        conditions = rule.get("conditions", [])
        actions = rule.get("actions", [])

        safe_id = self._sanitize_rule_id(rule_id)
        has_conditions = bool(conditions)

        # ── 注释头 ──
        lines = [
            f"  --- Rule: {rule_id}",
            f"  --- Actor: {actor_type} | Modality: {modality}",
            f"  --- Event: {event_pattern or 'UNRESOLVED'}"
            f" ({event.get('kind', '?')}: {event.get('expr', '')})",
            f"  --- Source: {source_doc} {source_sec}",
        ]

        # 条件注释
        if conditions:
            for i, c in enumerate(conditions):
                expr = c.get("expr", "") if isinstance(c, dict) else str(c)
                pred_info = ""
                if i < len(predicates) and predicates[i].get("resolved"):
                    matched = predicates[i].get("matched_predicates", [])
                    if matched:
                        pred_info = f" -> {matched[0]['name']}"
                lines.append(f"  --- Guard[{i}]: {expr}{pred_info}")

        # 动作注释
        for i, a in enumerate(actions):
            expr = a.get("expr", "") if isinstance(a, dict) else str(a)
            at = action_types[i] if i < len(action_types) else None
            at_str = at or "UNRESOLVED"
            lines.append(f"  --- Action[{i}] ({at_str}): {expr}")

        # ── 规则体 ──
        if has_conditions:
            lines.append(f"  crl [{safe_id}] :")
            lines.append(f"    < ID : {actor_type} | STATE >")
            lines.append(f"  =>")
            lines.append(f"    < ID : {actor_type} | STATE >")

            # 生成 guard 占位
            guard_parts: List[str] = []
            for i, pred in enumerate(predicates):
                if pred.get("resolved") and pred.get("matched_predicates"):
                    guard_parts.append(
                        f"({pred['matched_predicates'][0]['template']})"
                    )
                else:
                    cond_expr = conditions[i].get("expr", "?") if i < len(conditions) else "?"
                    guard_parts.append(f"true --- TODO: {cond_expr}")

            guard_str = " /\\ ".join(guard_parts) if guard_parts else "true"
            lines.append(f"  if {guard_str} .")
        else:
            lines.append(f"  rl [{safe_id}] :")
            lines.append(f"    < ID : {actor_type} | STATE >")
            lines.append(f"  =>")

            # 根据 action types 生成 RHS 占位
            rhs_comments: List[str] = []
            for i, at in enumerate(action_types):
                expr = actions[i].get("expr", "") if i < len(actions) else ""
                if at == "send_message":
                    rhs_comments.append(f"--- TODO: send message ({expr})")
                elif at == "cache_operation":
                    rhs_comments.append(f"--- TODO: cache operation ({expr})")
                elif at is None:
                    rhs_comments.append(f"--- TODO: UNRESOLVED action ({expr})")
                else:
                    rhs_comments.append(f"--- TODO: {at} ({expr})")

            lines.append(f"    < ID : {actor_type} | STATE >")
            for c in rhs_comments:
                lines.append(f"    {c}")
            # 去掉最后一个 TODO 注释的换行问题，在最后加 .
            lines.append(f"  .")

        lines.append("")
        return lines

    def _generate_skip_comment(self, rule: Dict[str, Any]) -> List[str]:
        """为不可生成的规则生成注释占位。"""
        rule_id = rule.get("id", "unknown")
        norm = rule.get("_normalized", {})
        return [
            f"  --- SKIPPED (not generatable): {rule_id}",
            f"  ---   resolved: {norm.get('resolved', '?')}",
            f"  ---   actor: {norm.get('actor_type', '?')}",
            f"  ---   event: {norm.get('event_pattern', '?')}",
            "",
        ]

    def _sanitize_rule_id(self, rule_id: str) -> str:
        """将规则 ID 转换为合法的 Maude 标识符。"""
        safe_id = rule_id.replace(" ", "-")
        if safe_id and safe_id[0].isdigit():
            safe_id = "r-" + safe_id
        return safe_id
